opam-version: "2.0"
name: "trillium-wfree"
version: "2.3.0"
synopsis: "Rocq development of the Trillium framework. This is a fork for Lawyer and wait-freedom projects."
maintainer: "Trillium Team"
authors: "Trillium Team"
license: "MIT"
build: ["./make-package" "trillium" "-j%{jobs}%"]
install: ["./make-package" "trillium" "install"]
depends: [
  "rocq-runtime" { (= "9.0.0") }
  "rocq-stdlib"
  "coq-iris" { (= "4.3.0") }
  "coq-stdpp" { (="1.11.0") }
  "coq-paco" { (= "4.2.3") }
]